services:
  postgres:
    image: postgres:16
    container_name: ferzan_postgres

    environment:
      POSTGRES_DB: ferzan_db
      POSTGRES_USER: ferzan_user
      POSTGRES_PASSWORD: ferzan_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
